BookStore/RazorWeb/Pages/AdminPage/AdminManageBook.cshtml.cs
using AutoMapper;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;
using System.Reflection.Metadata;

namespace RazorWeb.Pages.AdminPage
{
    public class AdminManageBookModel : PageModel
    {
        IBookService _book;
        ICategoryService _category;
        IImageService _image;
        IMapper _map;
        public AdminManageBookModel(IBookService book, ICategoryService category,IMapper map, IImageService image)
        {
            _book = book;
            _category = category;
            _map = map;
            _image = image;
        }
        [BindProperty]
        public List<BookDTO> books { get; set; }
        public List<Category> categories { get; set; }
        [BindProperty(SupportsGet = true)]
        public string search { get; set; }
        public string choice { get; set; }
        public int CurrentPage { get; set; } = 1;
        public int TotalPages { get; set; } = 1;
        public async Task OnGet(int pageNumber = 1)
        {
            if (pageNumber < 1)
                pageNumber = 1;
            CurrentPage = pageNumber;
            var listBook = await _book.GetBook();
            var listBookPage = await _book.TakePage(pageNumber,listBook);
            books =_map.Map<List<BookDTO>>(listBookPage).ToList();
            foreach(var book in books)
            {
                book.Image_URL = (await _image.GetAllImage(book.Book_Id)).ToList().First().Image_URL;
            }
            var listCategory = await _category.GetAllCategory();
            categories = listCategory.ToList();
            float i = ((float)listBook.ToList().Count()) / 4;
            var checkI = i - (float)Math.Round(i);
            if (checkI > 0)
            {
                TotalPages = (int)Math.Round(i + 0.5);
            }
            else
            {
                TotalPages = (int)Math.Round(i);
            }
        }
        public async Task<IActionResult> OnPostCategory()
        {
            var ID = Request.Form["choiceCategory"];
            return RedirectToPage("AdminManageCategoryBook", new{ idc = ID});
        }
    }
}

BookStore/RazorWeb/Pages/Cart.cshtml.cs
using System.Text.Json;
using BookStoreAPI.Core.DTO;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages
{
    public class CartModel : PageModel
    {

        
        public List<BookDTO> CartItems { get; set; }

        public float CartTotal => CartItems.Sum(item => item.Book_Price);
        
        public void OnGet()
        {
            GetItemFromSession();
        }

        public void OnPostDelete(Guid itemId)
        {
            GetItemFromSession();
            var itemToRemove = CartItems.FirstOrDefault(item => item.Book_Id == itemId);
            if (itemToRemove != null)
            {
                CartItems.Remove(itemToRemove);
                SaveCartItemsToSession();
            }
        }

        private void GetItemFromSession()
        {
            var cartItemsJson = HttpContext.Session.GetString("CartItems");
            if (!string.IsNullOrEmpty(cartItemsJson))
            {
                CartItems = JsonSerializer.Deserialize<List<BookDTO>>(cartItemsJson);
            }
            else
            {
                CartItems = new List<BookDTO>();
            }
        }

        private void SaveCartItemsToSession()
        {
            var cartItemsJson = JsonSerializer.Serialize(CartItems);
            HttpContext.Session.SetString("CartItems", cartItemsJson);
        }
    }
}

BookStore/RazorWeb/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookStore/RazorWeb/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IBookService _book;
        public IndexModel(ILogger<IndexModel> logger,IBookService book)
        {
            _logger = logger;
            _book = book;
        }

        public async Task OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/Invalid.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages
{
    public class InvalidModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/Login.cshtml.cs
using BookStoreAPI.Core.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Service.Service.IService;

namespace RazorWeb.Pages
{
    public class LoginModel : PageModel
    {
        IUserService _user;
        private readonly IHttpContextAccessor _context;
        public LoginModel(IUserService user, IHttpContextAccessor httpContextAccessor)
        {
            _user = user;
            _context = httpContextAccessor;
        }
        [BindProperty]
        public LoginDTO login { get; set; }
        [BindProperty]
        public int m_Message { get; set; } = 0;
        public async Task<IActionResult> OnPost()
        {
            var check = await _user.CheckLogin(login);
            if(check != null)
            {
                var loginJson = JsonConvert.SerializeObject(check);
                _context.HttpContext.Session.SetString("UserLogin", loginJson);
                switch (check.Role_Id)
                {
                    case 1:
                        return RedirectToPage("/AdminPage/AdminOverView");
                    case 2:
                        return RedirectToPage("/StaffPage/StaffManageNodifycshtml");
                    case 3:
                        return RedirectToPage("/SellerPage/SellerManageNodify");
                }
            }
            else
            {
                m_Message = 3;
            }
            return Page();
        }
        public async Task<IActionResult> OnPostEmail(string email)
        {
            var result = await _user.RecoverPassword(email);
            if (result)
            {
                m_Message = 1;
            }
            else
            {
                m_Message = 2;
            }
            return RedirectToPage("/Login");
        }


    }
}

BookStore/RazorWeb/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/AdminManageBook.cshtml
@page "/adminBook"
@model RazorWeb.Pages.AdminPage.AdminManageBookModel
@using BookStoreAPI.Core.DTO;
@{
}
 <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Admin Manage Books</title>
        <!-- link file CSS -->
        <link rel="stylesheet" href="./css/adminManageBooksStyle.css">
        <!-- BoxIcon CDN Link -->
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    </head>

    <body>

        <div class="header">
            <div class="header-menu">
                <!-- even menu sidebar -->
                <div class="sidebar-button__logo" style="padding-right:24px">
                    <div class="sidebar-button">
                        <i class='bx bx-menu sidebarBtn'></i>
                        <!-- <span class="dashboard">Dashboard</span> -->
                    </div>

                    <!-- div of logo -->
                    <div class="logo-details">
                        <img src="~/images/logo.jpg" width="100" height="100" alt="Logo Phuong Nam Bookstore">
                        <span class="logo_name">Book Store</span>
                    </div>
                </div>
                <div class="seachbox-profile">
                    <div class="wraper_searchbox_profile">
                        <div class="search-box">
                            <form action="adminBookAction?action=searchBook" method="POST">
                                <input type="text" placeholder="Search..." name="search" value="${search}">
                                <button type='submit'><i class='bx bx-search-alt-2'></i></button>
                            </form>
                        </div>
                        <div class="profile_details">
                            <img src="~/images/admin1.png" width="50px" height="50px" alt="image admin">
                            <div class="name_role">
                                <span class="name">${sessionScope.USER["fullName"]}</span>
                                <i class='bx bxs-chevron-down'></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="sidebar">
            <!-- link in sidebar -->
            <ul class="nav-links">
                <li>
                    <a href="./adminOverViewPage">
                        <i class='bx bx-home'></i>
                        <span class="links_name">Overview</span>
                    </a>
                </li>
                <li>
                    <a href="./adminManageInforDashboard">
                        <i class='bx bx-grid-alt'></i>
                        <span class="links_name">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="./adminShowListEmployees">
                        <i class='bx bx-user'></i>
                        <span class="links_name">Employees</span>
                    </a>
                </li>
                <li>
                    <a href="./adminShowListBookingRequest">
                        <i class='bx bx-import'></i>
                        <span class="links_name">Booking Request</span>
                    </a>
                </li>
                <li>
                    <a type="submit" href="adminBookAction?action=bookPage1">
                        <i class='bx bx-book'></i>
                        <span class="links_name">Books</span>
                    </a>
                </li>
                <li>
                    <a href="./adminShowListImportations">
                        <i class='bx bxs-report'></i>
                        <span class="links_name">Importation</span>
                    </a>
                </li>
                <!--                    <li>
                                        <a href="./adminShowListOrders">
                                            <i class='bx bx-list-ol'></i>
                                            <span class="links_name">Order</span>
                                        </a>
                                    </li>-->
                <li>
                    <a href="./logoutAction">
                        <i class='bx bx-log-out'></i>
                        <span class="links_name">Log out</span>
                    </a>
                </li>
            </ul>
        </div>

        <!-- home content -->
        <section class="home-section">
            @*Category*@
            <form class="formCategory" action="adminBookAction" method="POST">
                <spam class="categoryText">Category</spam>
                <select class="comboxCategory" name="action">
                    <option value="Romance">Romance</option>
                    <option value="Self-help">Self-help</option>
                    <option value="Novel">Novel</option>
                    <option value="Fantasy">Fantasy</option>
                </select>
                <button class="choice btn btn-secondary" type="submit">Go</button>
            </form><br/>
            <div class="itemList row">
                @*Display book*@
            @foreach (BookDTO b in Model.books)
            {
                <div class="item col-lg-6">
                    <form style="height: 325px;width: 450px"
                              action="adminBookAction?action=bookDetail&bookId=${b.book_Id}&categoryId=${b.category}"
                              method="POST">
                            <div class="border">
                                <img src="<c:url value="/images/${b.image_Book}"/>"/>
                                <p class="name">@b.Book_Title </p>
                                <p class="price">
                                @*<fmt:formatNumber value=@b.Book_Title type="number" />*@
                                    <p>@b.Book_Price</p>
                                    <small style="text-decoration:underline">đ</small>
                                    <button class="viewDetail btn btn-info" type="submit">View Detail
                                    </button>
                                <p>
                            </div>
                        </form>
                </div>
            }
            @*<c:forEach asp-for="books" var="b">
                    <div class="item col-lg-6">
                        <form style="height: 325px;width: 450px"
                              action="adminBookAction?action=bookDetail&bookId=${b.book_Id}&categoryId=${b.category}"
                              method="POST">
                            <div class="border">
                                <img src="<c:url value="/images/${b.image_Book}"/>"/>
                                <p class="name"></p>
                                <p class="price">
                                    <fmt:formatNumber value="${b.price_Book}" type="number"/>
                                    <small style="text-decoration:underline">đ</small>
                                    <button class="viewDetail btn btn-info" type="submit">View Detail
                                    </button>
                                <p>
                            </div>
                        </form>
                    </div>
                </c:forEach>*@
            </div>
            <div class="page row">
                <div class="col-lg-4"></div>
                <div class="col-lg-4 d-flex justify-content-center" >
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="adminBookAction?action=bookPage1">1</a></li>
                        <li class="page-item"><a class="page-link" href="adminBookAction?action=bookPage2">2</a></li>
                        <li class="page-item"><a class="page-link" href="adminBookAction?action=bookPage3">3</a></li>
                        <li class="page-item"><a class="page-link" href="adminBookAction?action=bookPage4">4</a></li>
                        <c:if test="${numLastBook>16}">
                            <li class="page-item"><a class="page-link" href="adminBookAction?action=bookPage5">5</a></li>
                        </c:if>
                        <c:if test="${numLastBook>20}">
                            <li class="page-item"><a class="page-link" href="adminBookAction?action=bookPage6">6</a></li>
                        </c:if>
                    </ul>
                </div>
                <div class="col-lg-4"></div>
            </div>
        </section>
        <script src="~/js/script.js"></script>

    </body>

BookStore/RazorWeb/Pages/Cart.cshtml
@page "/cart"
@model RazorWeb.Pages.CartModel
@{
}

<div class="home-section">
    <h1 class="display-4">Cart</h1>
    @if (Model.CartItems.Count == 0)
    {
        <p>Your cart is empty.</p>
    }
    else
    {
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.CartItems)
                {
                    <tr>
                        <td>@item.Book_Title</td>
                        <td>@item.Book_Price</td>
                        <td>@item.Book_Quantity</td>
                        <td>
                            <form asp-page-handler="delete" method="post">
                                <input type="hidden" name="itemId" value="@item.Book_Id" />
                                <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">Total:</td>
                    <td>@Model.CartTotal</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    
        <div>
            <a href="/checkout" class="btn btn-primary">Proceed to Checkout</a>
        </div>
    }

</div>

BookStore/RazorWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a asp-page="/AdminPage/AdminManageBook" class="nav-link">AdminBook</a>
    <a asp-page="/AdminPage/AdminManageEmployees" class="nav-link">ManageEmployee</a>
    <a asp-page="/AdminPage/AdminCreateNewEmployee" class="nav-link">CreateEmployee</a>
    <a asp-page="/AdminPage/AdminRequestImPortBook" class="nav-link">ManagaRequest</a>
</div>

BookStore/RazorWeb/Pages/Invalid.cshtml
@page
@model RazorWeb.Pages.InvalidModel
@{
}
<head>
    <title>Invalid Page</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- link file CSS -->
    <link rel="stylesheet" href="~/css/staffManageBookDetail.css">
</head>
<body>
    <h1>
        Invalid username or password
    </h1>
    <form action="loginPage">
        <button>Re-login</button>
    </form>
</body>

BookStore/RazorWeb/Pages/Login.cshtml
@page
@model RazorWeb.Pages.LoginModel
@{
    Layout = null;
}
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/loginFormStyle.css">
    @* Modal*@
    

    <style>
        .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.7); /* Màu mờ là màu đen */
            justify-content: center;
            align-items: center;
        }

        .modal-content {
            background-color: navajowhite;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            width:450px;
            height:150px;
        }

        .close-button {
            position: absolute;
            top: 10px;
            right: 10px;
            cursor: pointer;
            font-size:30px;
            color:red;
        }

      
    </style>
</head>

<body>

    <section class='login centered-element' id='login'>
        <div class='head'>
            <h1 class='company'>Phuong Nam Book Store</h1>
        </div>
        <p class='msg'>Welcome to Login</p>
        <div class='form'>
            <form method="post">
                <input type="text" asp-for="@Model.login.User_Account" placeholder='Username' class='text' id='username' ><br>
                <input type="password" asp-for="@Model.login.User_Password" placeholder='Password' class='password' ><br>
                <input type="submit" class='btn-login' value="Login" />
                <input type="reset" class="btn-cancel" value="Cancel" />
            </form>
            <p>Did you forget your password? <button type="button" class="btn btn-outline-info" onclick="openModal()">Recover Password</button></p>
        </div>
    </section>
    <!-- Modal -->
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close-button" onclick="closeModal()">&times;</span>
            <h2 style="font-size:25px;font-weight:100">Recover Password By Your Email</h2>
            <form method="post" asp-page-handler="Email">
                <input type="text" placeholder="Enter your email" class="form-control" name="email">
            <button type="submit" style="width:150px;margin-top:5px;margin: 10px auto; display: block;" class="btn btn-primary">Send Email</button>
            </form>
        </div>
    </div>
   
    <!-- partial -->
    <script src="~/js/LoginForm.js"></script>
    <!-- JavaScript cho modal -->
    <script>
        function openModal() {
            var modal = document.getElementById("myModal");
            modal.style.display = "flex";
        }

        function closeModal() {
            var modal = document.getElementById("myModal");
            modal.style.display = "none";
        }
       
      
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</body>

<script>
    $(document).ready(function () {
        $('.toast').toast('show');
    });
</script>