BookStore/RazorWeb/Pages/AdminPage/DeleteOrder.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml.Style;
using Service.Service;
using Service.Service.IService;

namespace RazorWeb.Pages.AdminPage
{
    public class DeleteOrderModel : PageModel
    {
		private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;
		public DeleteOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Order_Id { get; set; }
		[BindProperty(SupportsGet = true)]
		public Order orders { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			orders = _orderService.GetOrderByOrderId(Order_Id).Result;
			orderDetails = _orderDetailService.GetOrderDetailByOrderId(Order_Id).Result.ToList();
			var isSuccess = await _orderService.DeleteOrder(Order_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./AdminManageOrder");
		}
	}
}

BookStore/RazorWeb/Pages/SellerPage/DeleteOrder.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml.Style;
using Service.Service;
using Service.Service.IService;

namespace RazorWeb.Pages.SellerPage
{
    public class DeleteOrderModel : PageModel
    {
		private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;
		public DeleteOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Order_Id { get; set; }
		[BindProperty(SupportsGet = true)]
		public Order orders { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			orders = _orderService.GetOrderByOrderId(Order_Id).Result;
			orderDetails = _orderDetailService.GetOrderDetailByOrderId(Order_Id).Result.ToList();
			var isSuccess = await _orderService.DeleteOrder(Order_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./SellerManageOrder");
		}
	}
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageBooks.cshtml.cs
using AutoMapper;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Interface;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;
using static System.Reflection.Metadata.BlobBuilder;

namespace RazorWeb.Pages.SellerPage
{
    public class SellerManageBooksModel : PageModel
    {

        private readonly IBookService _book;
        private readonly ICategoryService _category;
        private readonly IImageService _image;
        private readonly IMapper _map;
        public SellerManageBooksModel(IBookService book, ICategoryService category, IMapper map, IImageService image)
        {
            _book = book;
            _category = category;
            _map = map;
            _image = image;
        }

        [BindProperty(SupportsGet = true)]
        public int SelectedCategory { get; set; } = -1;
        public List<BookDTO> Books { get; set; }
        public List<Category> Categories { get; set; }

        public int CurrentPage { get; set; } = 1;
        public int TotalPages { get; set; } = 1;
        public async Task OnGet(int pageNumber = 1)
        {
            if (pageNumber < 1)
                pageNumber = 1;
            Categories = _category.GetAllCategory().Result.ToList();
            if (SelectedCategory == -1)
            {
                CurrentPage = pageNumber;
                var listBook = await _book.GetBook();
                var listBookPage = await _book.TakePage(pageNumber, listBook);
                Books = _map.Map<List<BookDTO>>(listBookPage).ToList();
                foreach (var book in Books)
                {
                    book.Image_URL = (await _image.GetAllImage(book.Book_Id)).ToList().First().Image_URL;
                }
                var listCategory = await _category.GetAllCategory();
                float i = ((float)listBook.ToList().Count()) / 4;
                var checkI = i - (float)Math.Round(i);
                if (checkI > 0)
                {
                    TotalPages = (int)Math.Round(i + 0.5);
                }
                else
                {
                    TotalPages = (int)Math.Round(i);
                }
            }
            else
            {
                CurrentPage = pageNumber;
                var listBook = await _book.GetBookByCategory(SelectedCategory);
                var bookList = _map.Map<List<Book>>(listBook.ToList());
                var listBookPage = await _book.TakePage(pageNumber, bookList);
                Books = _map.Map<List<BookDTO>>(listBookPage).ToList();
                foreach (var book in Books)
                {
                    book.Image_URL = (await _image.GetAllImage(book.Book_Id)).ToList().First().Image_URL;
                }
                var listCategory = await _category.GetAllCategory();
                float i = ((float)listBook.ToList().Count()) / 4;
                var checkI = i - (float)Math.Round(i);
                if (checkI > 0)
                {
                    TotalPages = (int)Math.Round(i + 0.5);
                }
                else
                {
                    TotalPages = (int)Math.Round(i);
                }
            }
            
        }

    }
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageBooksDetail.cshtml.cs
using System.Text.Json;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.SellerPage
{
    public class SellerManageBooksDetailModel : PageModel
    {
        private readonly IBookService _bookService;

        public SellerManageBooksDetailModel(IBookService bookService)
        {
            _bookService = bookService;
        }
        
        public BookDetailDTO Book { get; set; }

        
        public Category Category { get; set; }

        private Dictionary<Guid, int> Cart { get; set; }

        public void OnGet(Guid bookId, int categoryId, string bookName)
        {
            Book = _bookService.GetBookById(bookId).Result;
        }

        public IActionResult OnPost(int cartQuantity, Guid bookId)
        {
            
            Book = _bookService.GetBookById(bookId).Result;
            
            // If the cart is not initialized yet, initialize it in the session
            if (HttpContext.Session.TryGetValue("Cart", out byte[] cartData))
            {
                Cart = JsonSerializer.Deserialize<Dictionary<Guid, int>>(cartData);
            }
            else
            {
                Cart = new Dictionary<Guid, int>();
            }

            if (Cart.TryGetValue(bookId, out int existingQuantity))
            {
                Cart[bookId] = existingQuantity + cartQuantity;
            } else
            {
                // If the book is not in the cart, add it with the specified quantity
                Cart.Add(bookId, cartQuantity);
            }
            
            // Save the cart back to the session
            HttpContext.Session.Set("Cart", JsonSerializer.SerializeToUtf8Bytes(Cart));
            
            // Redirect to the cart page
            return RedirectToPage("/SellerPage/SellerManageCart");
        }
    }
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageCart.cshtml.cs
using System.Text;
using System.Text.Json;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.SellerPage
{
    public class SellerManageCartModel : PageModel
    {
        private readonly IBookService _bookService;

        private readonly IHttpClientFactory _clientFactory;

        public SellerManageCartModel(IBookService bookService, IHttpClientFactory clientFactory)
        {
            _bookService = bookService;
            _clientFactory = clientFactory;
        }

        public Dictionary<Guid, int> Cart { get; set; } = default!;
        public Dictionary<Guid, BookDetailDTO> CartItems { get; set; } = new Dictionary<Guid, BookDetailDTO>();

        public void OnGet()
        {
           GetCart();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            GetCart();

            var loginJson = HttpContext.Session.GetString("UserLogin");
            if (loginJson == null)
            {
                return RedirectToPage("/login");
            }
            
            var user = JsonSerializer.Deserialize<User>(loginJson);
            
            int order_Quantity = Cart?.Count ?? 0;
            float order_Amount = GetTotalPrice();

            var data = new
            {
                user_Id = user.User_Id,
                order_Code = "string",
                order_Customer_Name = "string",
                order_Customer_Address = "string",
                order_Customer_Phone = "string",
                order_Quantity,
                order_Amount
            };

            var apiClient = _clientFactory.CreateClient("Api");

            // Call the API and handle the response
            var response = await apiClient.PostAsync("/api/order/createOrder",
                new StringContent(JsonSerializer.Serialize(data), Encoding.UTF8, "application/json"));
            if (response.IsSuccessStatusCode)
            {
                // Handle the successful response here
                var result = await response.Content.ReadAsStringAsync();
                var isSuccess = await PostOrderDetail();
                if (isSuccess)
                {
                    HttpContext.Session.Remove("Cart");
                    return RedirectToPage("/SellerPage/SellerManageBooks");
                }
                
            }
            else
            {
                // Handle the error response here
                Console.WriteLine(response.ReasonPhrase);
            }

            return Page();
        }

        public void OnPostCartUpdate(Guid bookId, int quantityUpdate)
        {
            GetCart();
            Cart[bookId] = quantityUpdate;
            HttpContext.Session.Set("Cart", JsonSerializer.SerializeToUtf8Bytes(Cart));
        }

        public void OnPostCartDelete(Guid bookId)
        {
            GetCart();
            Cart.Remove(bookId);
            HttpContext.Session.Set("Cart", JsonSerializer.SerializeToUtf8Bytes(Cart));
        }

        private async Task<bool> PostOrderDetail()
        {
            var status = false;
            var apiClient = _clientFactory.CreateClient("Api");
            
            string orderId = await GetOrderIdJustCreated();

            if (orderId == null)
            {
                return false;
            }
            
            foreach (var (key, value) in Cart)
            {
             
                var data = new
                {
                    order_Id = orderId,
                    book_Id = key,
                    order_Detail_Quantity = value,
                    order_Detail_Amount = CartItems[key].Book_Price * value,
                    order_Detail_Price = CartItems[key].Book_Price
                };
                
                var response = await apiClient.PostAsync("/api/orderDetail/createOrderDetail",
                    new StringContent(JsonSerializer.Serialize(data), Encoding.UTF8, "application/json"));

                if (response.IsSuccessStatusCode)
                {
                    var result = await response.Content.ReadAsStringAsync();
                    status = true;
                }
            }

            return status;
        }

        private async Task<string> GetOrderIdJustCreated()
        {
            var apiClient = _clientFactory.CreateClient("Api");
            var response = await apiClient.GetAsync("/api/order/getOrderIdJustCreated");
            
            var orderId = await response.Content.ReadAsStringAsync();

            if (orderId == "00000000-0000-0000-0000-000000000000")
            {
                return null;
            }

            orderId = orderId.Replace("\"", "");
            
            return orderId;
        }

        public float GetTotalPrice()
        {
            float sum = 0;

            if (Cart == null)
                return sum;

            foreach (var (key, value) in Cart)
            {
                sum += CartItems[key].Book_Price * value;
            }

            return sum;
        }

        private void GetCart()
        {
            if (HttpContext.Session.TryGetValue("Cart", out byte[] cartData))
            {
                Cart = JsonSerializer.Deserialize<Dictionary<Guid, int>>(cartData);
            }
            else
            {
                Cart = new Dictionary<Guid, int>();
            }
            
            foreach (var (key, value) in Cart)
            {
                CartItems.Add(key, _bookService.GetBookById(key).Result);
            }
        }
    }
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageCategoryBook.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages.SellerPage
{
    public class SellerManageCategoryBookModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageNodify.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages.SellerPage
{
    public class SellerManageNodifyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;
using BookStoreAPI.Core.Model;
using BookStoreAPI.Core.DiplayDTO;
using Microsoft.EntityFrameworkCore;

namespace RazorWeb.Pages.SellerPage
{
	public class SellerManageOrderModel : PageModel
	{
        private readonly IHttpContextAccessor _context;
        private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;

		public SellerManageOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}

		[BindProperty(SupportsGet = true)]
		public List<Order> orders { get; set; }
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }

		public void OnGet()
		{
            orders = _orderService.GetAllOrder().Result.ToList();
			orderDetails = _orderDetailService.GetDisplayOrderDetail().Result.ToList();
		}

	}
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageOrderHistory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages.SellerPage
{
    public class SellerManageOrderHistoryModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/DeleteOrder.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml.Style;
using Service.Service;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class DeleteOrderModel : PageModel
    {
		private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;
		public DeleteOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Order_Id { get; set; }
		[BindProperty(SupportsGet = true)]
		public Order orders { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			orders = _orderService.GetOrderByOrderId(Order_Id).Result;
			orderDetails = _orderDetailService.GetOrderDetailByOrderId(Order_Id).Result.ToList();
			var isSuccess = await _orderService.DeleteOrder(Order_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./StaffManageOrder");
		}
	}
}

BookStore/RazorWeb/Pages/SellerPage/DeleteOrder.cshtml
@page
@model RazorWeb.Pages.SellerPage.DeleteOrderModel
@{
}
<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this Order?</h3>

    <div class="container">
        <form method="post">
            <input type="hidden" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-page="./SellerManageOrder">Back to List Order</a>
            <div class="order">
				<div class="itemOrder">
					<p id="id"> Order: @Model.orders.Order_Code</p>
					<div><p id="date">Date: @Model.orders.Order_Date.ToString("dd-MM-yyyy")</p></div>
					<div><p id="fullname">Creator: @Model.orders.Order_Customer_Name</p></div>
				</div>
				<!--End Show Item Order-->

				<!--Start Show Item Order Detail-->
				@foreach(var DisplayOrderDetailDTO in Model.orderDetails)
				{
					<div class="orderDetail">
						<div class="itemDetail">

							<div>
								<img style="height: 100px;width: 100px"
										src="@DisplayOrderDetailDTO.Image_URL"/>
							</div>
							<div>
								<a href="sellerBookAction?action=bookDetail&amp">
											
								</a><br>
								<div class="price">
									<p id="quantity">x @DisplayOrderDetailDTO.Order_Detail_Quantity</p>
									<p id="total">
										@DisplayOrderDetailDTO.Order_Detail_Amount
										<small style="text-decoration:underline">đ</small>
									</p>
								</div>
							</div>
						</div>
					</div>
				}
				<div class="totalOrder">
					<!--
						<button id="btnAgain" data-toggle="modal" class="btn btn-danger"
							data-target="#myAgain${loop.index}">
							Buy Again
						</button>
					-->
						
					<p>Total( @Model.orders.Order_Quantity Book): </p>
					<p id="priceOrder"><fmt:formatNumber type="number" value=" @Model.orders.Order_Amount" /></p>
				</div>
			</div>
        </form>
    </div>
</div>

BookStore/RazorWeb/Pages/SellerPage/SellerManageBooks.cshtml
@page
@model RazorWeb.Pages.SellerPage.SellerManageBooksModel
@{
}

<form class="formCategory"  method="get">
    <spam class="categoryText">Category</spam>
    <select class="comboxCategory"  asp-for="SelectedCategory">
        <option value="-1" selected>All</option>
        @foreach(var category in Model.Categories)
        {
            <option value="@category.Category_Id">@category.Category_Name</option>
        }
    </select>
    <button class="choice btn btn-secondary" type="submit">Go</button>
</form><br/>
<div style="max-width: 960px" class="row mx-auto">
    @foreach (var book in Model.Books)
    {
        <div  class="item  mb-4 col-12 col-sm-6 col-md-3">
            <div class="border rounded p-4 d-flex flex-column align-items-center">
                <img style="object-fit: fill" class="w-100" src="@book.Image_URL" alt="image book"/><br/>
                <p class="name">@book.Book_Title</p>
                <p class="price">
                    <span>@book.Book_Price</span>
                    <small style="text-decoration: underline">đ</small>
                </p>
                <a href="SellerManageBooksDetail?bookId=@book.Book_Id&amp;categoryId=@book.Category_Id&amp;bookName=@book.Book_Title" style="line-height: 15px; width: 140px" class="viewDetail btn btn-info text-center " type="submit">
                    View Detail
                </a>
            </div>
        </div>
    }
</div>
<br />
@if (Model.TotalPages > 1)
{
    @if(Model.SelectedCategory == -1)
    {
        <div class="d-flex w-100 justify-content-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=1">First</a>
                    </li>
                    <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=@(Model.CurrentPage - 1)">Previous</a>
                    </li>
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                            <a class="page-link" href="?pageNumber=@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=@(Model.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=@Model.TotalPages">Last</a>
                    </li>
                </ul>
            </nav>
        </div>
    }
    @if (Model.SelectedCategory != -1)
    {
        <div class="d-flex w-100 justify-content-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="?SelectedCategory=@Model.SelectedCategory&pageNumber=1">First</a>
                    </li>
                    <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="?SelectedCategory=@Model.SelectedCategory&pageNumber=@(Model.CurrentPage - 1)">Previous</a>
                    </li>
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                            <a class="page-link" href="?SelectedCategory=@Model.SelectedCategory&pageNumber=@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                        <a class="page-link" href="?SelectedCategory=@Model.SelectedCategory&pageNumber=@(Model.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                        <a class="page-link" href="?SelectedCategory=@Model.SelectedCategory&pageNumber=@Model.TotalPages">Last</a>
                    </li>
                </ul>
            </nav>
        </div>
    }
}

BookStore/RazorWeb/Pages/SellerPage/SellerManageCart.cshtml
@page
@model RazorWeb.Pages.SellerPage.SellerManageCartModel
@{
}


<div class="home-section" style="margin-left:-400px;">
    <!-- home-content -->
    <h2 id="nameTable">YOUR CART</h2>
    @* <%--End Home Content--%> *@

    @* <%-- Write Body Code--%> *@

    @* <%-- Button Buy --%> *@
    @if (Model.Cart != null && Model.Cart.Count > 0)
    {
        @foreach (var (key, value) in Model.Cart)
        {
        @* <%--Start Show Item Cart--%> *@
            <div class="cartDetail">
                @* <%--Start Show Item--%> *@
                <div class="itemDetail d-flex justify-content-between">

                    @* Image *@
                    <div>
                        <img style="object-fit: contain ;height: 100px;width: 100px" src="@Model.CartItems[key].Image_URL[0]"/>
                    </div>

                    @* Content *@
                    <div class="d-flex flex-column flex-grow-1 px-4">
                        <p class="h5" id="nameBook"> @Model.CartItems[key].Book_Title</p><br>
                        <div class="price d-flex flex-column">
                            <p id="quantity">Quantity: @value</p>
                            <p id="total">
                                <span>Price: @Model.CartItems[key].Book_Price </span>
                                <small style="text-decoration:underline">đ</small>
                            </p>
                        </div>
                    </div>

                    @* Button Update and Delete *@
                    <div class="d-flex flex-column mr-4 ">
                        <button class="btn-outline-primary mb-4" style="font-size: 20px;border: none" id="btnUpdate" data-toggle="modal"
                                data-target="#CartModalUpdate_@key">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </button>
                        <button class="btn-outline-danger" style="font-size: 20px;border: none" data-toggle="modal" id="btnDelete"
                                data-target="#CartModalDelete_@key">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </div>
                </div>

                @* <%--Update Cart--%> *@
                <div class="modal fade" id="CartModalUpdate_@key" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <form asp-page-handler="CartUpdate" method="POST">
                            <div class="modal-content">

                                <header class="head-form">
                                    <h2>Update Quantity Book</h2>
                                </header>

                                <div class="modal-body">
                                    @* <%--Form --%> *@
                                    @* <%-- ID BOOK Insert To Inventory SQL--%> *@
                                    <input type="hidden" name="update"
                                           value="1"/>
                                    <input type="hidden" name="nameBook"
                                           value="@Model.CartItems[key].Book_Title"/>
                                    <input type="hidden" name="bookId" value="@key"/>
                                    @* <%-- DO Quantity Add to Cart --%> *@
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fa fa-address-book"></i>
                                                </span>
                                            </div>
                                            <input type="number" name="quantityUpdate" class="form-control input-sm"
                                                   style="font-size: 15px" placeholder="Quantity" value="@value" min="1" max="100">
                                        </div>
                                    </div>
                                </div>
                                <!-- Modal footer -->
                                <div class="modal-footer" id="modal-footer">
                                    <button type="submit" class="btn btn-info add ">Update</button>

                                    <button class="btn btn-warning xclose" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                @* <%--End Update Cart--%> *@

                @* <%--Delete Book Cart--%> *@
                <div class="modal fade" id="CartModalDelete_@key" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog ">
                        <form asp-page-handler="CartDelete" method="POST">
                            <div class="modal-content p-3">

                                <header class="head-form mb-0">
                                    <h2>Are You Sure To Delete The Book ?</h2>
                                </header>

                                <div class="modal-body">
                                    @* <%--Form --%> *@
                                        <input type="hidden" name="count"
                                               value="1"/>
                                        <input type="hidden" name="nameBook"
                                               value="${x.bookName}"/>
                                        <input type="hidden" name="bookId" value="@key"/>
                                        @* <%-- Are You Sure --%> *@
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-danger add">Delete</button>

                                    <button class="btn btn-warning " data-dismiss="modal">
                                        Close
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                @* <%--End Delete Book Cart--%> *@


            </div>
            <hr/>
        }


        <form method="POST">
            <div class="totalCart">
                <p id="priceCart">
                    <h1>
                        Total: <span>@Model.GetTotalPrice()</span>
                        <small style="text-decoration:underline">đ</small>
                    </h1>
                </p>
                <button id="btnBuy" class="btn btn-primary" type="submit">Buy</button>
            </div>
        </form>
    }
    else
    {
        <p class="text">You Do Not Have A Book In Your Cart</p>
        <form action="/SellerPage/SellerManageBooks" method="get">
            <button type="submit" class="btn btn-info btnAddBook">Add Book To Cart</button>
        </form>
    }

</div>