BookStore/RazorWeb/Pages/AdminPage/DeleteImportation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.AdminPage
{
    public class DeleteImportationModel : PageModel
    {
        private readonly IImportationService _importationService;
        public DeleteImportationModel(IImportationService importationService)
        {
            _importationService = importationService;
        }
        [BindProperty(SupportsGet = true)]
        public Guid Importation_Id { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var isSuccess = await _importationService.DeleteImport(Importation_Id);
            if (!isSuccess)
            {
                Console.WriteLine("delete not success");
            }
            return RedirectToPage("./AdminManageImportation");
        }
    }
}

BookStore/RazorWeb/Pages/AdminPage/DeleteInventory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.AdminPage
{
    public class DeleteInventoryModel : PageModel
    {
        private readonly IInventoryService _inventoryService;
        public DeleteInventoryModel(IInventoryService inventoryService)
        {
            _inventoryService = inventoryService;
        }
        [BindProperty(SupportsGet = true)]
        public Guid Inventory_Id { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var isSuccess = await _inventoryService.DeleteInventory(Inventory_Id);
            if (!isSuccess)
            {
                Console.WriteLine("delete not success");
            }
            return RedirectToPage("./AdminManageInventory");
        }
    }
}

BookStore/RazorWeb/Pages/AdminPage/DeleteOrder.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml.Style;
using Service.Service;
using Service.Service.IService;

namespace RazorWeb.Pages.AdminPage
{
    public class DeleteOrderModel : PageModel
    {
		private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;
		public DeleteOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Order_Id { get; set; }
		[BindProperty(SupportsGet = true)]
		public Order orders { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			orders = _orderService.GetOrderByOrderId(Order_Id).Result;
			orderDetails = _orderDetailService.GetOrderDetailByOrderId(Order_Id).Result.ToList();
			var isSuccess = await _orderService.DeleteOrder(Order_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./AdminManageOrder");
		}
	}
}

BookStore/RazorWeb/Pages/SellerPage/DeleteOrder.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml.Style;
using Service.Service;
using Service.Service.IService;

namespace RazorWeb.Pages.SellerPage
{
    public class DeleteOrderModel : PageModel
    {
		private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;
		public DeleteOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Order_Id { get; set; }
		[BindProperty(SupportsGet = true)]
		public Order orders { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			orders = _orderService.GetOrderByOrderId(Order_Id).Result;
			orderDetails = _orderDetailService.GetOrderDetailByOrderId(Order_Id).Result.ToList();
			var isSuccess = await _orderService.DeleteOrder(Order_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./SellerManageOrder");
		}
	}
}

BookStore/RazorWeb/Pages/StaffPage/DeleteImportation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class DeleteImportationModel : PageModel
	{
		private readonly IImportationService _importationService;
		public DeleteImportationModel(IImportationService importationService)
		{
			_importationService = importationService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Importation_Id { get; set; }

		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			var isSuccess = await _importationService.DeleteImport(Importation_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./StaffManageImportation");
		}
	}
}

BookStore/RazorWeb/Pages/StaffPage/DeleteInventory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class DeleteInventoryModel : PageModel
    {
        private readonly IInventoryService _inventoryService;
        public DeleteInventoryModel(IInventoryService inventoryService)
        {
            _inventoryService = inventoryService;
        }
        [BindProperty(SupportsGet = true)]
        public Guid Inventory_Id { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var isSuccess = await _inventoryService.DeleteInventory(Inventory_Id);
            if (!isSuccess)
            {
                Console.WriteLine("delete not success");
            }
            return RedirectToPage("./StaffManageInventory");
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/DeleteOrder.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml.Style;
using Service.Service;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class DeleteOrderModel : PageModel
    {
		private readonly IOrderService _orderService;
		private readonly IOrderDetailService _orderDetailService;
		public DeleteOrderModel(IOrderService orderService, IOrderDetailService orderDetailService)
		{
			_orderService = orderService;
			_orderDetailService = orderDetailService;
		}
		[BindProperty(SupportsGet = true)]
		public Guid Order_Id { get; set; }
		[BindProperty(SupportsGet = true)]
		public Order orders { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DisplayOrderDetailDTO> orderDetails { get; set; }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPost()
		{
			orders = _orderService.GetOrderByOrderId(Order_Id).Result;
			orderDetails = _orderDetailService.GetOrderDetailByOrderId(Order_Id).Result.ToList();
			var isSuccess = await _orderService.DeleteOrder(Order_Id);
			if (!isSuccess)
			{
				Console.WriteLine("delete not success");
			}
			return RedirectToPage("./StaffManageOrder");
		}
	}
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageBooks.cshtml.cs
using AutoMapper;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageBooksModel : PageModel
    {
        IBookService _book;
        ICategoryService _category;
        IImageService _image;
        IMapper _map;
        public StaffManageBooksModel(IBookService book, ICategoryService category, IMapper map, IImageService image)
        {
            _book = book;
            _category = category;
            _map = map;
            _image = image;
        }
        [BindProperty]
        public List<BookDTO> books { get; set; }
        public List<Category> categories { get; set; }
        [BindProperty(SupportsGet = true)]
        public string search { get; set; }
        public string choice { get; set; }
        public int CurrentPage { get; set; } = 1;
        public int TotalPages { get; set; } = 1;
        public async Task OnGet(int pageNumber = 1)
        {
            if (pageNumber < 1)
                pageNumber = 1;
            CurrentPage = pageNumber;
            var listBook = await _book.GetBook();
            var listBookPage = await _book.TakePage(pageNumber, listBook);
            books = _map.Map<List<BookDTO>>(listBookPage).ToList();
            foreach (var book in books)
            {
                book.Image_URL = (await _image.GetAllImage(book.Book_Id)).ToList().First().Image_URL;
            }
            var listCategory = await _category.GetAllCategory();
            categories = listCategory.ToList();
            float i = ((float)listBook.ToList().Count()) / 4;
            var checkI = i - (float)Math.Round(i);
            if (checkI > 0)
            {
                TotalPages = (int)Math.Round(i + 0.5);
            }
            else
            {
                TotalPages = (int)Math.Round(i);
            }
        }
        public async Task<IActionResult> OnPostCategory()
        {
            var ID = Request.Form["choiceCategory"];
            return RedirectToPage("StaffManageCategoryBook", new { idc = ID });
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageBooksDetail.cshtml.cs
using AutoMapper;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageBooksDetailModel : PageModel
    {
        private IBookService _book;
        private ICategoryService _category;
        private IMapper _map;
        private IInventoryService _inventory;
        private readonly IHttpContextAccessor _context;
        public StaffManageBooksDetailModel(IBookService book, IMapper mapper, ICategoryService category, IInventoryService inventory, IHttpContextAccessor context)
        {
            _book = book;
            _map = mapper;
            _category = category;
            _inventory = inventory;
            _context = context;
        }
        [BindProperty]
        public BookDetailDTO bookDetail { get; set; }
        [BindProperty]
        public List<Category> listCate { get; set; }
        [BindProperty(SupportsGet = true)]
        public Guid Book_Id { get; set; }
        [BindProperty(SupportsGet = true)]
        public InventoryDTO Inventorydto { get; set; }
        [BindProperty]
        public int m_Message { get; set; } = -1;
        public async Task OnGet()
        {
            bookDetail = await _book.GetBookById(Book_Id);
            var list = await _category.GetAllCategory();
            listCate = list.ToList();
        }
        public async Task<IActionResult> OnPost()
        {
            var book = _map.Map<Book>(bookDetail);
            var _update = await _book.UpdateBook(book);
            if (_update)
            {
                m_Message = 1;
                return Page();
            }
            m_Message = 0;
            return Page();
        }
        public async Task<IActionResult> OnPostAddInventory()
        {
            Book_Id = Inventorydto.Book_Id;
            bookDetail = await _book.GetBookById(Book_Id);
            if (Inventorydto.Inventory_Quantity > bookDetail.Book_Quantity || Inventorydto.Inventory_Quantity <= 0)
            {

                var list = await _category.GetAllCategory();
                listCate = list.ToList();
                m_Message = 3;
                return Page();
            }
            var data = _context.HttpContext.Session.GetString("UserLogin");
            var user = JsonConvert.DeserializeObject<User>(data);
            if (user == null) { }
            var inventory = _map.Map<Inventory>(Inventorydto);
            inventory.User_Id = user.User_Id;
            var IsCreate = await _inventory.CreateInventory(inventory);
            if (IsCreate)
            {
                m_Message = 2;
                return RedirectToPage("/StaffPage/StaffManageInventory");
            }
            m_Message = 3;
            return Page();
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageBooksHistory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageBooksHistoryModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageCategoryBook.cshtml.cs
using AutoMapper;
using AutoMapper.Execution;
using BookStoreAPI.Core.DTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageCategoryBookModel : PageModel
    {
        IBookService _book;
        ICategoryService _category;
        IMapper _mapper;
        IImageService _imageService;
        public StaffManageCategoryBookModel(IBookService book, ICategoryService category, IMapper mapper, IImageService imageService)
        {
            _book = book;
            _category = category;
            _mapper = mapper;
            _imageService = imageService;

		}
        [BindProperty]
        public string search { get; set; }
        public string nameCategory { get; set; }
        [BindProperty(Name = "idc", SupportsGet = true)]
        public int Id { get; set; }

        public List<BookDTO> books { get; set; }
        public int CurrentPage { get; set; } = 1;
        public int TotalPages { get; set; } = 1;

        public async Task OnGetAsync(int pageNumber = 1)
        {
            if (pageNumber < 1)
                pageNumber = 1;

            CurrentPage = pageNumber;
            var listBook = _book.GetBookByCategory(Id);
            var bookList = _mapper.Map<List<Book>>(listBook.Result.ToList());
            var listBookPage = await _book.TakePage(pageNumber, bookList);
            books = _mapper.Map<List<BookDTO>>(listBookPage).ToList();
			foreach (var book in books)
			{
				book.Image_URL = (await _imageService.GetAllImage(book.Book_Id)).ToList().First().Image_URL;
			}
			var name = _category.GetCategoryById(Id).Result.Category_Name;
            nameCategory = name;
            float i = ((float)listBook.Result.ToList().Count()) / 4;
            var checkI = i - (float)Math.Round(i);
            if (checkI > 0)
            {
                TotalPages = (int)Math.Round(i + 0.5);
            }
            else
            {
                TotalPages = (int)Math.Round(i);
            }

        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageImportation.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using BookStoreAPI.Core.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageImportationModel : PageModel
	{

		private readonly IImportationService _importationService;
		private readonly IImportationDetailService _ImportationDetailService;
		private readonly ICategoryService _categoryService;

		public StaffManageImportationModel(IImportationService importationService, IImportationDetailService ImportationDetailService)
		{
			_importationService = importationService;
			_ImportationDetailService = ImportationDetailService;
		}

		[BindProperty(SupportsGet = true)]
		public List<DisplayImportationDTO> Importations { get; set; }
		[BindProperty(SupportsGet = true)]
		public List<DiplayImportationDetailDTO> ImportationDetails { get; set; }

		public void OnGet()
		{
			Importations = _importationService.GetDiplayImport().Result.ToList();
			ImportationDetails = _ImportationDetailService.GetDiplayImportDetail().Result.ToList();
		}

	}
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageImportationHistory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageImportationHistoryModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageInventory.cshtml.cs
using BookStoreAPI.Core.DiplayDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.Service.IService;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageInventoryModel : PageModel
    {
        private readonly IInventoryService _inventoryService;

        public StaffManageInventoryModel(IInventoryService inventoryService)
        {
            _inventoryService = inventoryService;
        }

        [BindProperty]
        public List<DisplayInventoryDTO?> InventoryDTOs { get; set; }


        public async Task OnGet()
        {
            InventoryDTOs = (await _inventoryService.GetAllInventory()).Where(i => i.Is_Inventory_Status == true).ToList() ?? null;
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/StaffManageNodifycshtml.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorWeb.Pages.StaffPage
{
    public class StaffManageNodifycshtmlModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BookStore/RazorWeb/Pages/StaffPage/DeleteImportation.cshtml
@page
@model RazorWeb.Pages.StaffPage.DeleteImportationModel
@{
}
<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div class="container">
        <form method="post">
            <input type="hidden" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-page="./StaffManageImportation">Back to List</a>
        </form>
    </div>
</div>

BookStore/RazorWeb/Pages/StaffPage/DeleteInventory.cshtml
@page
@model RazorWeb.Pages.StaffPage.DeleteInventoryModel
@{
}
<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div class="container">
        <form method="post">
            <input type="hidden" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-page="./StaffManageInventory">Back to List</a>
        </form>
    </div>
</div>

BookStore/RazorWeb/Pages/StaffPage/DeleteOrder.cshtml
@page
@model RazorWeb.Pages.StaffPage.DeleteOrderModel
@{
}
<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this Order?</h3>

    <div class="container">
        <form method="post">
            <input type="hidden" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-page="./StaffManageOrder">Back to List Order</a>
        </form>
    </div>
</div>

BookStore/RazorWeb/Pages/StaffPage/StaffManageBooks.cshtml
@page 
@model RazorWeb.Pages.StaffPage.StaffManageBooksModel
@using BookStoreAPI.Core.DTO;
@using BookStoreAPI.Core.Model;
@{
}
<!-- home content -->
<section class="home-section">
    @*Category*@
    <form class="formCategory" method="POST">
        <spam class="categoryText">Category</spam>
        <select class="comboxCategory" name="choiceCategory">
            @foreach (Category c in Model.categories)
            {
                <option value="@c.Category_Id">@c.Category_Name</option>
            }
        </select>
        <button class="choice btn btn-secondary" asp-page-handler="Category" type="submit">Go</button>
    </form><br />
    <div class="itemList row" style="height:800px;margin-bottom:60px;">
        @*Display book*@
        @foreach (BookDTO b in Model.books)
        {
            <div class="item col-lg-4">
                <form >
                    <div class="border" style="height: 415px;width: 355px">
                        <img style="height: 230px; width: 330px;" src="@b.Image_URL" />
                        <p class="name">@b.Book_Title </p>
                        <p class="price"/>
                        <p style="font-size:15px;">@b.Book_Price<small style="text-decoration:underline">đ</small></p>
                        
                            @*call book detail page*@
                        <a class="viewDetail btn btn-info" asp-page="StaffManageBooksDetail" asp-route-Book_Id="@b.Book_Id">View Detail</a>
                        <p>
                    </div>
                </form>
            </div>
        }
    </div>
    <br />
    @if (Model.TotalPages > 1)
    {
        <div class="d-flex w-100 justify-content-center">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=1">First</a>
                    </li>
                    <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=@(Model.CurrentPage - 1)">Previous</a>
                    </li>
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                            <a class="page-link" href="?pageNumber=@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=@(Model.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                        <a class="page-link" href="?pageNumber=@Model.TotalPages">Last</a>
                    </li>
                </ul>
            </nav>
        </div>
    }
</section>

BookStore/RazorWeb/Pages/StaffPage/StaffManageBooksDetail.cshtml
@page
@model RazorWeb.Pages.StaffPage.StaffManageBooksDetailModel

@if (Model.m_Message == 1)
{
    <div id="success-notification" class="notification success">
        <span class="close" onclick="closeNotification()">&times;</span>
        <p style="color:white">Update book success!</p>
    </div>
}
@if (Model.m_Message == 0)
{
    <div id="success-notification" class="notification fail">
        <span class="close" onclick="closeNotification()">&times;</span>
        <p style="color:white">Update book fail!</p>
    </div>
}
@if (Model.m_Message == 2)
{
    <div id="success-notification" class="notification fail">
        <span class="close" onclick="closeNotification()">&times;</span>
        <p style="color:white">Update book fail!</p>
    </div>
}
@if (Model.m_Message == 3)
{
    <div id="success-notification" class="notification fail">
        <span class="close" onclick="closeNotification()">&times;</span>
        <p style="color:white">Create Inventory fail!</p>
    </div>
}
<!-- home content -->
<section class="home-section">

    <!-- home-content -->
    <div class="categoryText">
        <a style="color: black" asp-page="/StaffPage/StaffManageBooks">Category </a> >
        <a style="color: #17A2B8" asp-page="/StaffPage/StaffManageCategoryBook" asp-route-idc="@Model.bookDetail.Category_Id"> @Model.bookDetail.Category_Name</a>
    </div>
    <button class="Check"><i class="fa-regular fa-circle-check"></i></button>
    @*<%--  Item Book Need Show--%>*@
    <div class="itemList row">
        <div class="border" style="width:420px;height:375px;">
            <img src="@Model.bookDetail.Image_URL.First()" class="rounded" /><br />
        </div>
        <div class="item col-lg-5">
            <strong class="name">@Model.bookDetail.Book_Title</strong>
            <p class="price">
            <p style="font-size:25px;">@Model.bookDetail.Book_Price<small style="text-decoration:underline">đ</small></p>
            
            <p><br />
            <p class="quantity">Quantity: @Model.bookDetail.Book_Quantity</p>
            <p class="author">Author: <u>@Model.bookDetail.Book_Author</u></p>
            <p class="yearPublic">Year Of Public: @Model.bookDetail.Book_Year_Public</p>
            <button class="btn btn-danger" style="font-size:20px;" data-bs-toggle="modal" data-bs-target="#inventoryModal">
                Inventory
            </button>
        </div>

    </div>
    @*<%--   Show Description Book   --%>*@
    <div class="boxDescription">
        <div class="description">
            <strong>Information Detail</strong>
            <p class="text">@Model.bookDetail.Book_Description</p>
        </div>
    </div>
    @*<%-- End Show Item Book--%>*@


    @*<%--Form Add Inventory Book--%>*@
    <div class="modal fade" id="inventoryModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" style="margin-top: -70px;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel" style="margin-left:130px;font-size:28px; color:orange; font-weight:500">Create Inventory</h5>
                </div>
                <form method="post" asp-page-handler="addinventory">
                    <div class="modal-body">
                        <input type="hidden" asp-for="@Model.Inventorydto.Book_Id" value="@Model.bookDetail.Book_Id" />

                        <div class="mb-3">
                            <label for="title" class="form-label">Reason</label>
                            <input type="text" class="form-control" id="Reason" asp-for="@Model.Inventorydto.Inventory_Note" style="font-size:15px;">
                        </div>
                        <div class="mb-3">
                            <label for="title" class="form-label">Quantity</label>
                            <input type="text" class="form-control" id="quantity" asp-for="@Model.Inventorydto.Inventory_Quantity" style="font-size:15px;">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="font-size:15px;">Close</button>
                        <button type="submit" class="btn btn-primary" style="font-size:15px;">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @*<%--End Form Update Book--%>*@
</section>

BookStore/RazorWeb/Pages/StaffPage/StaffManageInventory.cshtml
@page
@model RazorWeb.Pages.StaffPage.StaffManageInventoryModel
@{
    int courter = 1;
}
<section class="home-section">
    <div class="home-content container" style="display:flex">
        <div>
            <h2 id="nameTable">LIST OF BOOK INVENTORY</h2>
        </div>
        
    </div>
    <table class="table" style="font-size:15px;">
        <thead>
            <tr>
                <th>.NO</th>
                <th>Image</th>
                <th>Name Book</th>
                <th>Quantity</th>
                <th>Reason</th>
                <th>Inventory Date</th>
                <th>Employee Implement</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var b in @Model.InventoryDTOs)
            {
                <tr>
                    <td>
                        @(courter++)
                    </td>
                    <td>
                        <div>
                            <img style="width:70px;height:80px;" src="@b.Image_URL" />
                        </div>

                    </td>
                    <td>
                        <p>@b.Book_Title</p>
                    </td>
                    <td>
                        <p>@b.Inventory_Quantity</p>
                    </td>
                    <td>
                        <p>@b.Inventory_Note</p>
                    </td>
                    <td>
                        <p>@b.Inventory_Date_Into</p>
                    </td>
                    <td>
                        <p>@b.User_Name</p>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</section>